---
- name: AutoDriver cuda
  hosts: target
  gather_facts: true
  become: true
  tasks:
    - name: Run cuda stage
      ansible.builtin.include_role:
        name: autodriver_gpu
        tasks_from: cuda.yml
